spring:
  application:
    name: feignhystrixdemo-consumer
  profiles:
    active:
      - prd

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

feign.hystrix.enabled: true