spring:
  application:
    name: feignhystrixdemo-consumer
  profiles:
    active:
      - prd

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

feign.hystrix.enabled: true