apiVersion: apps/v1
kind: Deployment
metadata:
  name: feignhystrixdemo-consumer
spec:
  selector:
    matchLabels:
      run: feignhystrixdemo-consumer
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        run: feignhystrixdemo-consumer
    spec:
      containers:
      - name: feignhystrixdemo-consumer
        image: apacpoc.azurecr.io/feignhystrixdemo-consumer:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080